{"number": 2600, "ref": "fix-async-from-sync-close", "login": "mhofman", "head": "f42aea089f66b47aebeb489323504ebeca0faff0", "base": "8dafd76d8a018bdec038885b1dfcd4565e413c1f", "title": "Normative: Close sync iterator when async wrapper yields rejection", "created_at": "2021-12-17T02:56:25Z", "updated_at": "2024-01-24T05:06:04Z", "revs": [{"hash": "f42aea089f66b47aebeb489323504ebeca0faff0", "parents": "12f246001eac94062fa6f717c0909b4919760e51", "author": "Kevin Gibbons", "date": "2024-01-23T20:55:40-08:00", "adate": "2023-12-28T12:38:04-08:00", "subject": "fixup: linter issues and feedback"}, {"hash": "12f246001eac94062fa6f717c0909b4919760e51", "parents": "8dafd76d8a018bdec038885b1dfcd4565e413c1f", "author": "Mathieu Hofman", "date": "2024-01-23T20:55:40-08:00", "adate": "2021-12-17T02:22:37+00:00", "subject": "Normative: Close sync iterator when async wrapper yields rejection"}]}